{{- define "helm-lib.csi.tpl" -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.CSI.ProviderClassName }}
spec:
  provider: azure
  secretObjects:
  {{- range $kvsecret := .Values.kvSecrets }}
  - data:
    - key: {{ $kvsecret.kvName }}
      objectName: {{ $kvsecret.kvName }}
    secretName:  {{ $kvsecret.k8Name }}
    type: Opaque  
  {{- end}}
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.serviceAccount.clientId }}
    keyvaultName: {{ .Values.CSI.kvName }}
    objects:  |
      array:
      {{- range $kvsecret := .Values.kvSecrets }}
        - |
          objectName: {{ $kvsecret.kvName }}
          objectType: secret
      {{- end }}

    tenantId: {{ .Values.serviceAccount.tenantId }}
{{- end -}}
{{- define "helm-lib.csi" -}} 3
{{- template "helm-lib.util.merge" (append . "helm-lib.csi.tpl") -}}
{{- end -}}